### PR TITLE
Remove `importc` in Nvidia wrapped types

### PR DESCRIPTION
**Pull request by Vindaar**
With our current Nvidia wrapper these are actively harmful. With them we get C compiler errors.

Also adds the `cuCtxSetLimit` function, which allows setting custom limits (like increasing the stack size).

### CODE REVIEW

**Comment by mratsim** [comment]
I'm curious about your Nim compiler + C compiler + LLVM lib + Cuda version as I don't get any error.

Unless cuda.h is imported somewhere, the compiler has no way to find a pointer mismatch as there are no other definition.

And matching the name is easier when debugging codegen.

**Comment by Vindaar** [comment]
This is with:
- Nim version 2.2.4 (latest stable `f7145dd26efeeeb6eeae6fff649db244d81b212d`)
- GCC version: `14.2.1 20250405`
- or Clang version: `17.0.6`
- CUDA 12.8

and happens on both the LLVM as well as NVRTC test cases with this kind of error:

```
~/src/nim/constantine/nimcache/tests/gpu/t_load_store.nim/@m..@s..@sconstantine@splatforms@sabis@snvidia_abi.nim.c:41:96: error: unknown type name 'CUcontext'
   41 | typedef N_NOCONV_PTR(tyEnum_CUresult__KUCbFqldGRY17wzdY1nAfA, tyProc__t0sUhPdNf3lioKRScnpKgw) (CUcontext* pctx_p0, NU32 flags_p1, NI32 dev_p2);
      |                                                                                                ^~~~~~~~~
~/src/nim/constantine/nimcache/tests/gpu/t_load_store.nim/@m..@s..@sconstantine@splatforms@sabis@snvidia_abi.nim.c:42:98: error: unknown type name 'CUcontext'
   42 | typedef N_NOCONV_PTR(tyEnum_CUresult__KUCbFqldGRY17wzdY1nAfA, tyProc__GmeIR9bOmRNBA9apcjf2wYMw) (CUcontext* module_p0, void* image_p1);
      |                                                                                                  ^~~~~~~~~
~/src/nim/constantine/nimcache/tests/gpu/t_load_store.nim/@m..@s..@sconstantine@splatforms@sabis@snvidia_abi.nim.c:43:96: error: unknown type name 'CUcontext'
   43 | typedef N_NOCONV_PTR(tyEnum_CUresult__KUCbFqldGRY17wzdY1nAfA, tyProc__FBYpOsbG3oqEYhGAzyEkdA) (CUcontext* kernel_p0, CUmodule module_p1, NIM_CHAR* fnName_p2);
      |                                                                                                ^~~~~~~~~
```

I don't see any weird Nim config flags in my configuration either that would explain this. Note that I don't really understand why this happens either. It just seems like when the `importc` is there, it produces function signatures with those types in place, but does not actually include / define the corresponding types in the helper C files. 

This may just be a Nim compiler bug.

**Comment by mratsim** [comment]
It's a regression between nim 2.2.0 and nim 2.2.2

**Comment by mratsim** [comment]
And just to make sure, it's not fixed by adding `nodecl` like in #512 as they are not builtin the compiler.

I'm not sure why it works in my case with Nim 2.2.0 but not in https://github.com/nim-lang/Nim/issues/24604

**Comment by mratsim** [comment]
Minimal repro:

```Nim
const libCuda = "(libcuda.so|cuda.lib)"

{.pragma: v1, noconv, importc, dynlib: libCuda.}
{.pragma: v2, noconv, importc: "$1_v2", dynlib: libCuda.}

type
  CUdevice* = distinct int32
  CUcontext* {.importc.} = distinct pointer

template check(status: cint) =
  let code = status # ensure that the input expression is evaluated once only
  if code != 0:
    writeStackTrace()
    stderr.write(astToStr(status) & " " & $instantiationInfo() & " exited with error: " & $code & '\n')
    quit 1

proc cuInit*(flags: uint32): cint {.v1.}
proc cuDeviceGet*(device: var CUdevice, ordinal: int32): cint {.v1.}
proc cuCtxCreate*(pctx: var CUcontext, flags: uint32, dev: CUdevice): cint {.v2.}

let deviceID = 0'i32
check cuInit(uint32 deviceID)

var cuDevice: CUdevice
check cuDeviceGet(cuDevice, deviceID)

var ctx: CUcontext
check cuCtxCreate(ctx, 0, cuDevice)
```

**Comment by mratsim** [comment]
So distinct void pointer are now using the importc name instead of `void *`

image

**Comment by mratsim** [comment]
Even more minimal:

```Nim
type CUcontext* {.importc.} = distinct pointer

proc foo(ctx: CUcontext) =
  echo "Hello"

var ctx: CUcontext
ctx.foo()
```

**Comment by mratsim** [comment]
Raised upstream https://github.com/nim-lang/Nim/issues/25137

I left the importc to avoid name mangling but instead of CUcontext, we had `void*`

So maybe we actually should use `exportc` but oh well, this might avoid LTO collisions if constantine is build with another Cuda library that imports Nvidia types.
